exclude: ["sass", ".sass-cache", "config.rb", "docsrc", "node_modules", "vendor"]
permalink: /blog/:year/:month/:day/:title.html

markdown: redcarpet
redcarpet:
  extensions: ['with_toc_data']

# pygments: true
# include: ['api','js']
host: '::'
